import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  { id: 'c1', name: 'Canva Template', slug: 'canva-template', icon: 'LayoutTemplate' },
  { id: 'c2', name: 'Lightroom Preset', slug: 'lightroom-preset', icon: 'Camera' },
  { id: 'c3', name: 'PSD Template', slug: 'psd-template', icon: 'Image' },
  { id: 'c4', name: 'Mockup Design', slug: 'mockup-design', icon: 'Monitor' },
  { id: 'c5', name: 'Premium Font', slug: 'premium-font', icon: 'Type' },
  { id: 'c6', name: 'UI Kit', slug: 'ui-kit', icon: 'Layers' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    category_id: 'c1',
    title: 'Minimalist Social Media Social Media Kit Canva',
    slug: 'minimalist-social-media-kit-canva',
    description: 'A clean and minimalist social media template kit for Canva. Perfect for influencers, brands, and creators wanting to maintain a cohesive and professional Instagram grid.',
    thumbnail: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
    price: 150000,
    discount: 20,
    sales: 120,
    rating: 4.8,
  },
  {
    id: 'p2',
    category_id: 'c2',
    title: 'Moody Cinematic Lightroom Presets',
    slug: 'moody-cinematic-lightroom-presets',
    description: 'Transform your photos with instant moody and cinematic tones. Includes 10 premium desktop and mobile presets.',
    thumbnail: 'https://images.unsplash.com/photo-1558236714-d0a6c382bcca?w=800&q=80',
    price: 250000,
    discount: 50,
    sales: 340,
    rating: 4.9,
  },
  {
    id: 'p3',
    category_id: 'c6',
    title: 'E-commerce App UI Kit (Figma)',
    slug: 'ecommerce-app-ui-kit',
    description: 'A comprehensive modern mobile app UI Kit for e-commerce. Over 80+ screens ready to kickstart your next big project.',
    thumbnail: 'https://images.unsplash.com/photo-1541560052-5e137f229371?w=800&q=80',
    price: 350000,
    discount: 0,
    sales: 55,
    rating: 4.7,
  },
  {
    id: 'p4',
    category_id: 'c4',
    title: 'Premium Brand Identity Mockups',
    slug: 'premium-brand-identity-mockups',
    description: 'Photorealistic stationary and branding mockup set. Easily editable via Smart Objects. High resolution 4K.',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&q=80',
    price: 120000,
    discount: 10,
    sales: 89,
    rating: 4.5,
  },
  {
    id: 'p5',
    category_id: 'c1',
    title: 'Real Estate Instagram Post Templates',
    slug: 'real-estate-instagram-post-canva',
    description: 'Boost your real estate business with these easy to edit Canva templates. Includes property listing, open house, and market updates designs.',
    thumbnail: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
    price: 99000,
    discount: 0,
    sales: 210,
    rating: 4.6,
  },
  {
    id: 'p6',
    category_id: 'c5',
    title: 'Aesthetic Serif Font Bundle',
    slug: 'aesthetic-serif-font-bundle',
    description: 'A beautiful collection of 5 premium serif fonts perfectly suited for luxury branding, editorial design, and sophisticated logos.',
    thumbnail: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?w=800&q=80',
    price: 180000,
    discount: 30,
    sales: 420,
    rating: 5.0,
  }
];
